config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  namespace :api, {format: 'json'} do
    resources :calendar, only: %i[show]
    resources :study_time_records, only: %i[destroy]
  end

  resources :sessions, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discord_bot.rb
class DiscordBot
  def initialize
    @bot = Discordrb::Commands::CommandBot.new token: ENV['DISCORD_BOT_TOKEN'],
                                               prefix: 'stup!'
  end

  def start
    @bot.command :s, description: '学習時間の記録を開始します。' do |event|
      user = User.find_by(uid: event.user.id)
      if user.nil?
        event.respond "ユーザーが登録されていません。"
      else
        @records = StudyTimeRecord.where(user_id: user.id)
        @start_time = Time.now.strftime("%Y-%m-%d %H:%M")
        if @records.empty?
          user.study_time_records.create(start_at: @start_time)
          event.respond "学習を開始しました。#{@start_time}"
        else
          if @records.last.end_at.nil?
            event.respond "前回の学習が終了していません。"
          else
            user.study_time_records.create(start_at: @start_time)
            event.respond "学習を開始しました。#{@start_time}"
          end
        end
      end
    end

    @bot.command :e, description: '学習時間の記録を終了します。' do |event|
      user = User.find_by(uid: event.user.id)
      if user.nil?
        event.respond "ユーザーが登録されていません。"
      else
        @records = StudyTimeRecord.where(user_id: user.id)
        @end_time = Time.now.strftime("%Y-%m-%d %H:%M")
        if @records.last.end_at.nil?
          user.study_time_records.last.update(end_at: @end_time)
          event.respond "学習を終了しました。#{@end_time}"
        else
          event.respond '学習が開始されていません。'
        end
      end
    end
    @bot.run
  end

  private

  # 最新の学習記録を取得する
  def get_current_study_records

  end

end

app/models/study_time_record.rb
class StudyTimeRecord < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :study_time_records
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(uid: user_params[:uid]) do |user|
        user.update(user_params)
      end
    end

    private

    def user_params_from_auth_hash(auth_hash)
      {
        name: auth_hash.info.name,
        email: auth_hash.info.email,
        image: auth_hash.info.image,
        uid: auth_hash.uid,
      }
    end
  end
end

app/controllers/api/calendar_controller.rb
class Api::CalendarController < ActionController::API
  def show
    @study_time_records = User.find(params[:id])
                              .study_time_records
  end
end

app/controllers/api/study_time_records_controller.rb
class Api::StudyTimeRecordsController < ActionController::API
  include SessionsHelper

  def destroy
    User.find(current_user.id).study_time_records.find(params[:id]).destroy
    head :no_content
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :check_logged_in

  def check_logged_in
    return if current_user

    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_logged_in, only: :index
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logged_in, only: :create

  def create
    if (user = User.find_or_create_from_auth_hash(auth_hash))
      log_in user
    end
    redirect_to root_path
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return unless (user_id = session[:user_id])

    @current_user ||= User.find_by(id: user_id)
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hello_vue/_hello.html.slim
div.text-black
  h1
    | HelloVue#index
  div#app

app/views/home/index.html.slim
- if current_user
  = render 'shared/header'
  div.flex.justify-center
    div#calendar.mx-5 value = current_user.id
    div#chart.mx-5
- else
  = render 'welcome/welcome'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PrototypeStup
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = yield
    = render 'shared/footer'

app/views/shared/_footer.html.slim
footer
  .footer.footer-center.p-10.border.border-black.bg-green-300.text-black
    | フッターを作成予定

app/views/shared/_header.html.slim
header
  .w-full.h-12.flex.bg-red-300
    div.text-black
      p
        | ヘッダー作成予定
    div
      = image_tag current_user.image, size: '35x35'
    div.text-black
      = link_to "ログアウト", log_out_path

app/views/welcome/_welcome.html.slim
div.container.mx-auto.my-4.text-black
  h1.text-2xl
    | すたっぷ
  p
    | 学習時間を記録する時、時計を意識していませんか？
  p
    | 学習時間をExcelなどに記録していませんか？
  p
    | すたっぷは
    a.text-xl Discord Bot
    | を連携させることにより
  p
    | コマンド一つであなたの学習時間を記録・管理することができます。
  == button_to "学習を記録する", "/auth/discord", method: :post, data: { turbo: false }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"

app/views/welcome/index.html.slim
div.container.mx-auto.my-4
  h1.text-2xl
    | すたっぷ
  p
    | 学習時間を記録する時、時計を意識していませんか？
  p
    | 学習時間をExcelなどに記録していませんか？
  p
    | すたっぷは
    a.text-xl Discord Bot
    | を連携させることにより
  p
    | コマンド一つであなたの学習時間を記録・管理することができます。